# Railway configuration file
# This explicitly tells Railway how to build and deploy the project

[build]
builder = "NIXPACKS"
buildCommand = "npm run build"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/"
healthcheckTimeout = 300

# Override any auto-detected settings
[deploy.override]
startCommand = "node dist/server.js"